language: cpp

os:
  - linux

sudo: required
dist: trusty

env:
  - PYTHON=2.7
  - PYTHON=3.5
  - PYTHON=3.6

before_install:
  # miniconda
  - travis_retry wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

  # create miniconda env
  - conda create --yes -n geomeppy python=$PYTHON
  - source activate geomeppy

install:
  - pip install -e .[testing]

before_script:
  - flake8 --count geomeppy
  - if [[ $PYTHON == 3.6 ]]; then mypy --ignore-missing-imports geomeppy || :; fi  # force a zero return code

script:
  # run all tests in tests and check coverage of the geomeppy dir
  - py.test -v --cov-config .coveragerc --cov=geomeppy tests

after_success:
  # coverage reporting on CodeCov
  - if [[ $PYTHON == 3.6 ]]; then codecov; fi

deploy:
  provider: pypi
  user: JamieBull
  password:
    secure: "INjtDQJQ/C26wFn0I62Et805PPnI4B/9WgHMsIRh1U7zXPrYt2N7+VcpbsgJRmxxObfeZstgfNalX9MadpTslVnEPtDIiYEyFgrJGrGSuOWTumAAiqo8mWkcP8F9Gpk69ZErF2pOZ7LzrwA0gqpCzwfYzwPO3skVFAmmQyRecs+JniMQXRpO6NlUGEp9HoPII0MqKkw9j0g8zAwsz3auw34eBlYnJFstVk56KdOiYAsIvfeQ/pbc3MHLm8c6Tjeqe29YV903qiqb0UQcw0k9AzMdz1USOQ7+j0rUxQFr6wyLL7/q6kjWYHIzwQhUB0MdMRKXS7s6AXxeJqbUTT0CVIVSKcyoRDip5nwDDNqmtnGbg+Jp1qZWNPVYe5dKW55h4qYC/7Pn1kohUvxfJIZbYb26HPsE1xi/c6nVRmVosJPZ8mCRAVXhq9BY16827mLnpamJkdCyyJVYRZvU5WLa0zZqypqP4pjLUyzKDUBwr8tcTHcia7wGy4eUOMFQLT1I7bWJbLAlY+RHjIeZJ/60OvhYx9PVWDnPbuG0QiomejBlPzMkkjUhXhMwWNHyq0FdsQEhrPmzlNbXctBBtGhzr7c+p2xaKYwf36OUp3jaPLwwqZ4NEG5vAmWVB95yQugtTNCainzN4y1V+0o7tf8q68C4fG4/LoXizjlWoEb+/p4="
